#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
 elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='osx'   
fi

if [[ $platform == 'osx' ]]; then
  docker rm -f iop
  docker run -d --privileged=true -P -p 10000:10000 -p 11000:11000 -p 2122:2122 -p 50010:50010 -p 50020:50020 -p 50030:50030 -p 50070:50070 -p 50075:50075 -p 50090:50090 -p 50111:50111 -p 60010:60010 -p 8000:8000 -p 8020:8020 -p 8021:8021 -p 8081:8081 -p 8088:8088 -p 8440:8440 -p 8043:8043 -p 8441:8441 -p 8670:8670 -p 8888:8888 --name iop -h ambari.luck.com lresende/iop:4.0 /etc/bootstrap.sh -d

  IP="$(docker exec iop /bin/hostname -i)"
else
  sudo docker rm -f iop
  sudo docker run -d --privileged=true -P -p 10000:10000 -p 11000:11000 -p 2122:2122 -p 50010:50010 -p 50020:50020 -p 50030:50030 -p 50070:50070 -p 50075:50075 -p 50090:50090 -p 50111:50111 -p 60010:60010 -p 8000:8000 -p 8020:8020 -p 8021:8021 -p 8081:8081 -p 8088:8088 -p 8440:8440 -p 8043:8043 -p 8441:8441 -p 8670:8670 -p 8888:8888 --name iop -h ambari.luck.com lresende/iop:4.0 /etc/bootstrap.sh -d

  IP="$(sudo docker exec iop /bin/hostname -i)"
fi

echo "IOP host running at: $IP"
